### ISSUE TITLE
Non google email addresses not supported

### ISSUE THREAD

**Issue by gfontenot** [los-verdes/digital-membership#2]
I don't use a gmail address as my primary address, and so the existing login method doesn't work for me.

**Comment by jeffwecan** [comment]
@gfontenot What would be your preferred way to log in? Ultimately the current login provider (Google OAuth2) is just a means to have a third-party provider authenticate folks' email addresses (to match them up with the email address connected to the membership orders).

**Comment by gfontenot** [comment]
I think ideally I'd want to access the membership card via the LV store somehow once I'm already authed with the account connected to the membership.

I use FastMail for email, but I don't think we should be building oauth connections for every possible email provider.

**Comment by jeffwecan** [comment]
Yeah I'm in agreement generally there. I have yet to see any avenues for directly integrating with the existing Squarespace accounts but I would go with something like that if at all possible. 

We could do regular 'ole username and password auth as another option maybe? I.e., would that work for you? 

Pending some currently unbeknownst to me direct Squarespace integration options of course.

**Comment by jeffwecan** [comment]
Or what if you just entered an email address and got sent an email with a membership card attached? Right now I have a pkpass setup mostly implemented and those files can be read by Apple wallet and various Android apps.

**Comment by jeffwecan** [comment]
For the record, the email distribution bit's implementation was primarily handled in https://github.com/los-verdes/digital-membership/pull/8 and I'm considering it done at this point. I am happy to take any additional feedback on that process via a new issue / #team-dev-work thread though!
